name: Build and Publish
on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GKE_KEY: ${{ secrets.GKE_KEY }}
  GITHUB_SHA: ${{ github.sha }}
  GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
  IMAGE: ufsp-view

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      
    # Setup gcloud CLI
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }} 
        
    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
        
    # Build the Docker image
    - name: Build
      run: |
        docker build \
          -t "eu.gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          https://github.com/Rotfuks/unnamedFruitScanProject.git#master:view
    
    # Docker login
    - name: Docker Login
      run: |
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io
    
    
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        gcloud docker -- push "eu.gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA"
