name: Build and Publish
on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GKE_KEY: ${{ secrets.GKE_KEY }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: ufsp-view

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}    
        
    - run: |
        # Get GCR Docker Creds Compoonent
        gcloud components install docker-credential-gcr

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
        
    - run: |
        # Configure GCR Docker Creds Compoonent
        docker-credential-gcr configure-docker
        
    # Build the Docker image
    - name: Build
      run: |
        docker build \
          -t "gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          https://github.com/Rotfuks/unnamedFruitScanProject.git#master:view
          
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        gcloud docker push "gcr.io/$GKE_PROJECT/$IMAGE:$GITHUB_SHA"
